/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ccatalogo;
import javax.swing.JOptionPane;

/**
 *
 * @author Laptop HP 255 G10
 */
public class Catalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Catalogo.class.getName());
public controlador.ColaCarrito carrito = new controlador.ColaCarrito();
    /**
     * Creates new form Catalogo
     */
  public Catalogo() {
    this.setUndecorated(true); 
    initComponents();
    this.setLocationRelativeTo(null);
    
    jScrollPane1.setBorder(null);
    jScrollPane1.setHorizontalScrollBarPolicy(
        javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    this.setSize(870, 500);
    
    final int[] posX = {0};
    final int[] posY = {0};
    jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent e) {
            posX[0] = e.getX();
            posY[0] = e.getY();
        }
    });
    jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent e) {
            setLocation(getX() + e.getX() - posX[0],
                        getY() + e.getY() - posY[0]);
        }
    });

    BotonX.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent e) {
            posX[0] = e.getX();
            posY[0] = e.getY();
        }
    });
    BotonX.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent e) {
            setLocation(getX() + e.getX() - posX[0],
                        getY() + e.getY() - posY[0]);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Catalogo11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bcatalogo = new javax.swing.JButton();
        Bfavoritos = new javax.swing.JButton();
        Bpedidos = new javax.swing.JButton();
        Bcarrito = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        Bperfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Icatalogo = new javax.swing.JLabel();
        Ifavoritos = new javax.swing.JLabel();
        Ipedidos = new javax.swing.JLabel();
        Icarrito = new javax.swing.JLabel();
        Iperfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tarjetaproducto = new Clases.PanelRound();
        IconTarjeta = new javax.swing.JLabel();
        panelRound3 = new Clases.PanelRound();
        NombreProducto1 = new javax.swing.JLabel();
        Descripcion1 = new javax.swing.JLabel();
        Precio1 = new javax.swing.JLabel();
        Bagregar1 = new javax.swing.JButton();
        Tarjetaproducto1 = new Clases.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        panelRound5 = new Clases.PanelRound();
        NombreProducto2 = new javax.swing.JLabel();
        Descripcion2 = new javax.swing.JLabel();
        Precio2 = new javax.swing.JLabel();
        Bagregar2 = new javax.swing.JButton();
        Tarjetaproducto2 = new Clases.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        panelRound7 = new Clases.PanelRound();
        NombreProducto3 = new javax.swing.JLabel();
        Descripcion3 = new javax.swing.JLabel();
        Precio3 = new javax.swing.JLabel();
        Bagregar3 = new javax.swing.JButton();
        Tarjetaproducto3 = new Clases.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        panelRound9 = new Clases.PanelRound();
        NombreProducto4 = new javax.swing.JLabel();
        Descripcion4 = new javax.swing.JLabel();
        Precio4 = new javax.swing.JLabel();
        Bagregar4 = new javax.swing.JButton();
        Tarjetaproducto4 = new Clases.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        panelRound11 = new Clases.PanelRound();
        NombreProducto5 = new javax.swing.JLabel();
        Descripcion5 = new javax.swing.JLabel();
        Precio5 = new javax.swing.JLabel();
        Bagregar5 = new javax.swing.JButton();
        Tarjetaproducto5 = new Clases.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        panelRound13 = new Clases.PanelRound();
        NombreProducto6 = new javax.swing.JLabel();
        Descripcion6 = new javax.swing.JLabel();
        Precio6 = new javax.swing.JLabel();
        Bagregar6 = new javax.swing.JButton();
        panelRound1 = new Clases.PanelRound();
        CatalogoProducto = new javax.swing.JLabel();
        BotonX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Catalogo11.setBackground(new java.awt.Color(204, 204, 204));
        Catalogo11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/iconoMZ.png"))); // NOI18N

        Bcatalogo.setBackground(new java.awt.Color(51, 255, 255));
        Bcatalogo.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bcatalogo.setText("Catalogo");
        Bcatalogo.setBorder(null);
        Bcatalogo.setBorderPainted(false);
        Bcatalogo.setContentAreaFilled(false);
        Bcatalogo.setFocusPainted(false);
        Bcatalogo.addActionListener(this::BcatalogoActionPerformed);

        Bfavoritos.setBackground(new java.awt.Color(51, 255, 255));
        Bfavoritos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bfavoritos.setText("Favoritos");
        Bfavoritos.setBorder(null);
        Bfavoritos.setBorderPainted(false);
        Bfavoritos.setContentAreaFilled(false);
        Bfavoritos.setFocusPainted(false);
        Bfavoritos.addActionListener(this::BfavoritosActionPerformed);

        Bpedidos.setBackground(new java.awt.Color(51, 255, 255));
        Bpedidos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bpedidos.setText("pedidos");
        Bpedidos.setBorder(null);
        Bpedidos.setBorderPainted(false);
        Bpedidos.setContentAreaFilled(false);
        Bpedidos.setFocusPainted(false);
        Bpedidos.addActionListener(this::BpedidosActionPerformed);

        Bcarrito.setBackground(new java.awt.Color(51, 255, 255));
        Bcarrito.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bcarrito.setText("Carrito");
        Bcarrito.setBorder(null);
        Bcarrito.setBorderPainted(false);
        Bcarrito.setContentAreaFilled(false);
        Bcarrito.setFocusPainted(false);
        Bcarrito.addActionListener(this::BcarritoActionPerformed);

        Bsalir.setBackground(new java.awt.Color(51, 255, 255));
        Bsalir.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bsalir.setText("Salir");
        Bsalir.setBorder(null);
        Bsalir.setBorderPainted(false);
        Bsalir.setContentAreaFilled(false);
        Bsalir.setFocusPainted(false);
        Bsalir.addActionListener(this::BsalirActionPerformed);

        Bperfil.setBackground(new java.awt.Color(51, 255, 255));
        Bperfil.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bperfil.setText("Perfil");
        Bperfil.setBorder(null);
        Bperfil.setBorderPainted(false);
        Bperfil.setContentAreaFilled(false);
        Bperfil.setFocusPainted(false);
        Bperfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bperfil.addActionListener(this::BperfilActionPerformed);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/salida (1).png"))); // NOI18N

        Icatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/revista-catalogo.png"))); // NOI18N

        Ifavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/corazon (1).png"))); // NOI18N

        Ipedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/reloj-tres (1).png"))); // NOI18N

        Icarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/carrito-de-compras.png"))); // NOI18N

        Iperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/usuario.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(Icatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ifavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bfavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ipedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bpedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Icarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iperfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bperfil)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Icatalogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ifavoritos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ipedidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Icarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Iperfil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bcatalogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bfavoritos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bcarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bpedidos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bsalir)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Catalogo11.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 880, 60));

        Tarjetaproducto.setBackground(new java.awt.Color(0, 204, 204));
        Tarjetaproducto.setRoundBottomLeft(20);
        Tarjetaproducto.setRoundBottomRight(20);
        Tarjetaproducto.setRoundTopLeft(20);
        Tarjetaproducto.setRoundTopRight(20);

        IconTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/airpods.png"))); // NOI18N

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);

        NombreProducto1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreProducto1.setText("AirPods 3 generación");

        Descripcion1.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion1.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion1.setText(" AirPods con cancelación");

        Precio1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Precio1.setText("$ 2.500.000");

        Bagregar1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bagregar1.setText("Agregar");
        Bagregar1.addActionListener(this::Bagregar1ActionPerformed);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(NombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bagregar1))
                    .addComponent(Descripcion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreProducto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio1)
                    .addComponent(Bagregar1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout TarjetaproductoLayout = new javax.swing.GroupLayout(Tarjetaproducto);
        Tarjetaproducto.setLayout(TarjetaproductoLayout);
        TarjetaproductoLayout.setHorizontalGroup(
            TarjetaproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaproductoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(IconTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TarjetaproductoLayout.setVerticalGroup(
            TarjetaproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TarjetaproductoLayout.createSequentialGroup()
                .addComponent(IconTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Catalogo11.add(Tarjetaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        Tarjetaproducto1.setBackground(new java.awt.Color(0, 204, 204));
        Tarjetaproducto1.setRoundBottomLeft(20);
        Tarjetaproducto1.setRoundBottomRight(20);
        Tarjetaproducto1.setRoundTopLeft(20);
        Tarjetaproducto1.setRoundTopRight(20);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/iphone 17.png"))); // NOI18N

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);

        NombreProducto2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreProducto2.setText("Iphone 16 Pro Max");

        Descripcion2.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion2.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion2.setText("celular con 8GB de ram");

        Precio2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Precio2.setText("$ 2.500.000");

        Bagregar2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bagregar2.setText("Agregar");
        Bagregar2.addActionListener(this::Bagregar2ActionPerformed);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addComponent(NombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addComponent(Precio2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bagregar2)))
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreProducto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio2)
                    .addComponent(Bagregar2))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout Tarjetaproducto1Layout = new javax.swing.GroupLayout(Tarjetaproducto1);
        Tarjetaproducto1.setLayout(Tarjetaproducto1Layout);
        Tarjetaproducto1Layout.setHorizontalGroup(
            Tarjetaproducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tarjetaproducto1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Tarjetaproducto1Layout.setVerticalGroup(
            Tarjetaproducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tarjetaproducto1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Catalogo11.add(Tarjetaproducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        Tarjetaproducto2.setBackground(new java.awt.Color(0, 204, 204));
        Tarjetaproducto2.setRoundBottomLeft(20);
        Tarjetaproducto2.setRoundBottomRight(20);
        Tarjetaproducto2.setRoundTopLeft(20);
        Tarjetaproducto2.setRoundTopRight(20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/camara.png"))); // NOI18N

        panelRound7.setBackground(new java.awt.Color(255, 255, 255));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);

        NombreProducto3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreProducto3.setText("Camara Profesional");

        Descripcion3.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion3.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion3.setText("camara de alta definición");

        Precio3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Precio3.setText("$ 2.500.000");

        Bagregar3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bagregar3.setText("Agregar");
        Bagregar3.addActionListener(this::Bagregar3ActionPerformed);

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Descripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addComponent(NombreProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addComponent(Precio3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bagregar3)))
                .addContainerGap())
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreProducto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio3)
                    .addComponent(Bagregar3))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout Tarjetaproducto2Layout = new javax.swing.GroupLayout(Tarjetaproducto2);
        Tarjetaproducto2.setLayout(Tarjetaproducto2Layout);
        Tarjetaproducto2Layout.setHorizontalGroup(
            Tarjetaproducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tarjetaproducto2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Tarjetaproducto2Layout.setVerticalGroup(
            Tarjetaproducto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tarjetaproducto2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Catalogo11.add(Tarjetaproducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        Tarjetaproducto3.setBackground(new java.awt.Color(0, 204, 204));
        Tarjetaproducto3.setRoundBottomLeft(20);
        Tarjetaproducto3.setRoundBottomRight(20);
        Tarjetaproducto3.setRoundTopLeft(20);
        Tarjetaproducto3.setRoundTopRight(20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/reloj.png"))); // NOI18N

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setRoundBottomLeft(20);
        panelRound9.setRoundBottomRight(20);

        NombreProducto4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreProducto4.setText("Reloj Inteligente");

        Descripcion4.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion4.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion4.setText("reloj economico digital ");

        Precio4.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Precio4.setText("$ 2.500.000");

        Bagregar4.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bagregar4.setText("Agregar");
        Bagregar4.addActionListener(this::Bagregar4ActionPerformed);

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Descripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound9Layout.createSequentialGroup()
                        .addComponent(NombreProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRound9Layout.createSequentialGroup()
                        .addComponent(Precio4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bagregar4)))
                .addContainerGap())
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreProducto4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio4)
                    .addComponent(Bagregar4))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout Tarjetaproducto3Layout = new javax.swing.GroupLayout(Tarjetaproducto3);
        Tarjetaproducto3.setLayout(Tarjetaproducto3Layout);
        Tarjetaproducto3Layout.setHorizontalGroup(
            Tarjetaproducto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tarjetaproducto3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Tarjetaproducto3Layout.setVerticalGroup(
            Tarjetaproducto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tarjetaproducto3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Catalogo11.add(Tarjetaproducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        Tarjetaproducto4.setBackground(new java.awt.Color(0, 204, 204));
        Tarjetaproducto4.setRoundBottomLeft(20);
        Tarjetaproducto4.setRoundBottomRight(20);
        Tarjetaproducto4.setRoundTopLeft(20);
        Tarjetaproducto4.setRoundTopRight(20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/macbook.png"))); // NOI18N

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setRoundBottomLeft(20);
        panelRound11.setRoundBottomRight(20);

        NombreProducto5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreProducto5.setText("MacBook Air 13");

        Descripcion5.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion5.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion5.setText("Portatil de marca apple");

        Precio5.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Precio5.setText("$ 2.500.000");

        Bagregar5.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bagregar5.setText("Agregar");
        Bagregar5.addActionListener(this::Bagregar5ActionPerformed);

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Descripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound11Layout.createSequentialGroup()
                        .addComponent(NombreProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRound11Layout.createSequentialGroup()
                        .addComponent(Precio5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bagregar5)))
                .addContainerGap())
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreProducto5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio5)
                    .addComponent(Bagregar5))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout Tarjetaproducto4Layout = new javax.swing.GroupLayout(Tarjetaproducto4);
        Tarjetaproducto4.setLayout(Tarjetaproducto4Layout);
        Tarjetaproducto4Layout.setHorizontalGroup(
            Tarjetaproducto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tarjetaproducto4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRound11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Tarjetaproducto4Layout.setVerticalGroup(
            Tarjetaproducto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tarjetaproducto4Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Catalogo11.add(Tarjetaproducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        Tarjetaproducto5.setBackground(new java.awt.Color(0, 204, 204));
        Tarjetaproducto5.setRoundBottomLeft(20);
        Tarjetaproducto5.setRoundBottomRight(20);
        Tarjetaproducto5.setRoundTopLeft(20);
        Tarjetaproducto5.setRoundTopRight(20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/parlante_1.png"))); // NOI18N

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setRoundBottomLeft(20);
        panelRound13.setRoundBottomRight(20);

        NombreProducto6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreProducto6.setText("Parlante Pequeño");

        Descripcion6.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion6.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion6.setText("parlante resistente al agua");

        Precio6.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Precio6.setText("$ 2.500.000");

        Bagregar6.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bagregar6.setText("Agregar");
        Bagregar6.addActionListener(this::Bagregar6ActionPerformed);

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Descripcion6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound13Layout.createSequentialGroup()
                        .addComponent(NombreProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRound13Layout.createSequentialGroup()
                        .addComponent(Precio6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bagregar6)))
                .addContainerGap())
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreProducto6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio6)
                    .addComponent(Bagregar6))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout Tarjetaproducto5Layout = new javax.swing.GroupLayout(Tarjetaproducto5);
        Tarjetaproducto5.setLayout(Tarjetaproducto5Layout);
        Tarjetaproducto5Layout.setHorizontalGroup(
            Tarjetaproducto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tarjetaproducto5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Tarjetaproducto5Layout.setVerticalGroup(
            Tarjetaproducto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tarjetaproducto5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Catalogo11.add(Tarjetaproducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, -1, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        CatalogoProducto.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        CatalogoProducto.setText("Catalogo de Productos");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(CatalogoProducto)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CatalogoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Catalogo11.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, 30));

        BotonX.setBackground(new java.awt.Color(204, 0, 0));
        BotonX.setText("X");
        BotonX.setBorder(null);
        BotonX.setBorderPainted(false);
        BotonX.setFocusPainted(false);
        BotonX.addActionListener(this::BotonXActionPerformed);
        Catalogo11.add(BotonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 40, 20));

        jScrollPane1.setViewportView(Catalogo11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bagregar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar6ActionPerformed
    carrito.agregar(NombreProducto6.getText(), Precio6.getText());
    }//GEN-LAST:event_Bagregar6ActionPerformed

    private void Bagregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar5ActionPerformed
        carrito.agregar(NombreProducto5.getText(), Precio5.getText());
    }//GEN-LAST:event_Bagregar5ActionPerformed

    private void Bagregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar4ActionPerformed
         carrito.agregar(NombreProducto4.getText(), Precio4.getText());
    }//GEN-LAST:event_Bagregar4ActionPerformed

    private void Bagregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar3ActionPerformed
            carrito.agregar(NombreProducto3.getText(), Precio3.getText());

    }//GEN-LAST:event_Bagregar3ActionPerformed

    private void Bagregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar2ActionPerformed
     carrito.agregar(NombreProducto2.getText(), Precio2.getText());

    }//GEN-LAST:event_Bagregar2ActionPerformed

    private void Bagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar1ActionPerformed
       carrito.agregar(NombreProducto1.getText(), Precio1.getText());
    
    }//GEN-LAST:event_Bagregar1ActionPerformed

    private void BperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BperfilActionPerformed
       JOptionPane.showMessageDialog(null, "Sección Perfil - Próximamente.");
    }//GEN-LAST:event_BperfilActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
         int conf = JOptionPane.showConfirmDialog(null,
        "¿Desea salir de MercaEZ?", "Salir",
        JOptionPane.YES_NO_OPTION);
    if (conf == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_BsalirActionPerformed

    private void BcarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcarritoActionPerformed
        carrito.mostrarCarrito();
    }//GEN-LAST:event_BcarritoActionPerformed

    private void BpedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpedidosActionPerformed
       JOptionPane.showMessageDialog(null, "Sección Pedidos - Próximamente.");
    }//GEN-LAST:event_BpedidosActionPerformed

    private void BfavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfavoritosActionPerformed
         JOptionPane.showMessageDialog(null, "Sección Favoritos - Próximamente.");
    }//GEN-LAST:event_BfavoritosActionPerformed

    private void BcatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcatalogoActionPerformed
       JOptionPane.showMessageDialog(null, "Ya estás en el Catálogo.");
    }//GEN-LAST:event_BcatalogoActionPerformed

    private void BotonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonXActionPerformed
        int conf = JOptionPane.showConfirmDialog(null,
    "¿Desea salir de MercaEZ?", "Salir",
    JOptionPane.YES_NO_OPTION);
if (conf == JOptionPane.YES_OPTION) {
    System.exit(0);
}
    }//GEN-LAST:event_BotonXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Catalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregar1;
    private javax.swing.JButton Bagregar2;
    private javax.swing.JButton Bagregar3;
    private javax.swing.JButton Bagregar4;
    private javax.swing.JButton Bagregar5;
    private javax.swing.JButton Bagregar6;
    private javax.swing.JButton Bcarrito;
    private javax.swing.JButton Bcatalogo;
    private javax.swing.JButton Bfavoritos;
    private javax.swing.JButton BotonX;
    private javax.swing.JButton Bpedidos;
    private javax.swing.JButton Bperfil;
    private javax.swing.JButton Bsalir;
    private javax.swing.JPanel Catalogo11;
    private javax.swing.JLabel CatalogoProducto;
    private javax.swing.JLabel Descripcion1;
    private javax.swing.JLabel Descripcion2;
    private javax.swing.JLabel Descripcion3;
    private javax.swing.JLabel Descripcion4;
    private javax.swing.JLabel Descripcion5;
    private javax.swing.JLabel Descripcion6;
    private javax.swing.JLabel Icarrito;
    private javax.swing.JLabel Icatalogo;
    private javax.swing.JLabel IconTarjeta;
    private javax.swing.JLabel Ifavoritos;
    private javax.swing.JLabel Ipedidos;
    private javax.swing.JLabel Iperfil;
    private javax.swing.JLabel NombreProducto1;
    private javax.swing.JLabel NombreProducto2;
    private javax.swing.JLabel NombreProducto3;
    private javax.swing.JLabel NombreProducto4;
    private javax.swing.JLabel NombreProducto5;
    private javax.swing.JLabel NombreProducto6;
    private javax.swing.JLabel Precio1;
    private javax.swing.JLabel Precio2;
    private javax.swing.JLabel Precio3;
    private javax.swing.JLabel Precio4;
    private javax.swing.JLabel Precio5;
    private javax.swing.JLabel Precio6;
    private Clases.PanelRound Tarjetaproducto;
    private Clases.PanelRound Tarjetaproducto1;
    private Clases.PanelRound Tarjetaproducto2;
    private Clases.PanelRound Tarjetaproducto3;
    private Clases.PanelRound Tarjetaproducto4;
    private Clases.PanelRound Tarjetaproducto5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound11;
    private Clases.PanelRound panelRound13;
    private Clases.PanelRound panelRound3;
    private Clases.PanelRound panelRound5;
    private Clases.PanelRound panelRound7;
    private Clases.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
}
