/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ccatalogo;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.awt.Dimension;

/**
 *
 * @author Laptop HP 255 G10
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelAdmin.class.getName());

    /**
     * Creates new form PanelAdmin
     */
public PanelAdmin() {
    this.setUndecorated(true);
    initComponents();
    this.setLocationRelativeTo(null);
    
    pnlScroll.setBorder(null);
    pnlScroll.setHorizontalScrollBarPolicy(
        javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    pnlScroll.setVerticalScrollBarPolicy(
    javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
    this.setSize(870, 500);
    
    
    pnlContenido.setPreferredSize(new Dimension(890, 900));
    pnlScroll.setViewportView(pnlContenido);
    
    
    pnlCarritoVacio.setVisible(false);
    pnlCarritoLleno.setVisible(true);
    
    pnlCarritoVacio.getParent().setComponentZOrder(pnlCarritoVacio, 0);
    pnlCarritoLleno.getParent().setComponentZOrder(pnlCarritoLleno, 1);
    
    this.setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlScroll = new javax.swing.JScrollPane();
        pnlContenido = new javax.swing.JPanel();
        BarraMZ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bcatalogo = new javax.swing.JButton();
        Bfavoritos = new javax.swing.JButton();
        Bpedidos = new javax.swing.JButton();
        Bcarrito = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        Bperfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Icatalogo = new javax.swing.JLabel();
        Ifavoritos = new javax.swing.JLabel();
        Ipedidos = new javax.swing.JLabel();
        Icarrito = new javax.swing.JLabel();
        Iperfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        txtNombre = new javax.swing.JTextField();
        NombreL = new javax.swing.JLabel();
        agregarPL = new javax.swing.JLabel();
        PrecioL = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        INimagenL = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        DescricionL = new javax.swing.JLabel();
        txtDescricion = new javax.swing.JTextField();
        pnlCarritoVacio = new Clases.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlCarritoLleno = new Clases.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        panelRound3 = new Clases.PanelRound();
        panelRound4 = new Clases.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Descripcion1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlScroll.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlScroll.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraMZ.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/iconoMZ.png"))); // NOI18N

        Bcatalogo.setBackground(new java.awt.Color(51, 255, 255));
        Bcatalogo.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bcatalogo.setText("Catalogo");
        Bcatalogo.setBorder(null);
        Bcatalogo.setBorderPainted(false);
        Bcatalogo.setContentAreaFilled(false);
        Bcatalogo.setFocusPainted(false);
        Bcatalogo.addActionListener(this::BcatalogoActionPerformed);

        Bfavoritos.setBackground(new java.awt.Color(51, 255, 255));
        Bfavoritos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bfavoritos.setText("Favoritos");
        Bfavoritos.setBorder(null);
        Bfavoritos.setBorderPainted(false);
        Bfavoritos.setContentAreaFilled(false);
        Bfavoritos.setFocusPainted(false);
        Bfavoritos.addActionListener(this::BfavoritosActionPerformed);

        Bpedidos.setBackground(new java.awt.Color(51, 255, 255));
        Bpedidos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bpedidos.setText("pedidos");
        Bpedidos.setBorder(null);
        Bpedidos.setBorderPainted(false);
        Bpedidos.setContentAreaFilled(false);
        Bpedidos.setFocusPainted(false);
        Bpedidos.addActionListener(this::BpedidosActionPerformed);

        Bcarrito.setBackground(new java.awt.Color(51, 255, 255));
        Bcarrito.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bcarrito.setText("Carrito");
        Bcarrito.setBorder(null);
        Bcarrito.setBorderPainted(false);
        Bcarrito.setContentAreaFilled(false);
        Bcarrito.setFocusPainted(false);
        Bcarrito.addActionListener(this::BcarritoActionPerformed);

        Bsalir.setBackground(new java.awt.Color(51, 255, 255));
        Bsalir.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bsalir.setText("Salir");
        Bsalir.setBorder(null);
        Bsalir.setBorderPainted(false);
        Bsalir.setContentAreaFilled(false);
        Bsalir.setFocusPainted(false);
        Bsalir.addActionListener(this::BsalirActionPerformed);

        Bperfil.setBackground(new java.awt.Color(51, 255, 255));
        Bperfil.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bperfil.setText("Perfil");
        Bperfil.setBorder(null);
        Bperfil.setBorderPainted(false);
        Bperfil.setContentAreaFilled(false);
        Bperfil.setFocusPainted(false);
        Bperfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bperfil.addActionListener(this::BperfilActionPerformed);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/salida (1).png"))); // NOI18N

        Icatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/revista-catalogo.png"))); // NOI18N

        Ifavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/corazon (1).png"))); // NOI18N

        Ipedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/reloj-tres (1).png"))); // NOI18N

        Icarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/carrito-de-compras.png"))); // NOI18N

        Iperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/usuario.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Logo1.png"))); // NOI18N

        javax.swing.GroupLayout BarraMZLayout = new javax.swing.GroupLayout(BarraMZ);
        BarraMZ.setLayout(BarraMZLayout);
        BarraMZLayout.setHorizontalGroup(
            BarraMZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMZLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(Icatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ifavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bfavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ipedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bpedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Icarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iperfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        BarraMZLayout.setVerticalGroup(
            BarraMZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraMZLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraMZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BarraMZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bperfil)
                        .addGroup(BarraMZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Icatalogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ifavoritos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ipedidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Icarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Iperfil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bcatalogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bfavoritos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bcarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bpedidos)))
                    .addGroup(BarraMZLayout.createSequentialGroup()
                        .addGroup(BarraMZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bsalir)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlContenido.add(BarraMZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 880, 60));

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnlContenido.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1030, 880, 30));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        NombreL.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NombreL.setText("Nombre");

        agregarPL.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        agregarPL.setText("agregar producto");

        PrecioL.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        PrecioL.setText("precio");

        txtPrecio.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        INimagenL.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        INimagenL.setText("Ingresar Imagen");

        txtImagen.setBackground(new java.awt.Color(204, 204, 204));
        txtImagen.addActionListener(this::txtImagenActionPerformed);

        DescricionL.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        DescricionL.setText("Descripción");

        txtDescricion.setBackground(new java.awt.Color(204, 204, 204));
        txtDescricion.addActionListener(this::txtDescricionActionPerformed);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreL)
                            .addComponent(PrecioL)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INimagenL)
                            .addComponent(DescricionL)
                            .addComponent(txtDescricion, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(agregarPL)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(agregarPL)
                .addGap(44, 44, 44)
                .addComponent(NombreL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PrecioL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(INimagenL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(DescricionL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlContenido.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 770, 420));

        pnlCarritoVacio.setBackground(new java.awt.Color(204, 204, 204));
        pnlCarritoVacio.setRoundBottomLeft(20);
        pnlCarritoVacio.setRoundBottomRight(20);
        pnlCarritoVacio.setRoundTopLeft(20);
        pnlCarritoVacio.setRoundTopRight(20);
        pnlCarritoVacio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel12.setText("productos (1)");
        pnlCarritoVacio.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel4.setText("NO HAY PRODUCTOS");
        pnlCarritoVacio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 113, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        pnlCarritoVacio.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 247, -1, -1));

        pnlContenido.add(pnlCarritoVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        pnlCarritoLleno.setBackground(new java.awt.Color(204, 204, 204));
        pnlCarritoLleno.setRoundBottomLeft(20);
        pnlCarritoLleno.setRoundBottomRight(20);
        pnlCarritoLleno.setRoundTopLeft(20);
        pnlCarritoLleno.setRoundTopRight(20);
        pnlCarritoLleno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel8.setText("productos (1)");
        pnlCarritoLleno.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 20, -1, -1));

        panelRound3.setMaximumSize(new java.awt.Dimension(600, 100));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        panelRound4.setBackground(new java.awt.Color(204, 204, 255));
        panelRound4.setMaximumSize(new java.awt.Dimension(100, 102));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundTopLeft(20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/airpods2.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel5.setText("Airpods Pro Generación 3 ");

        Descripcion1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Descripcion1.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion1.setText(" AirPods con cancelación");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/lapiz.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/basura.png"))); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(12, 12, 12))))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCarritoLleno.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 88, 720, -1));

        pnlContenido.add(pnlCarritoLleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 760, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcatalogoActionPerformed
        JOptionPane.showMessageDialog(null, "Ya estás en el Catálogo.");
    }//GEN-LAST:event_BcatalogoActionPerformed

    private void BfavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfavoritosActionPerformed
        JOptionPane.showMessageDialog(null, "Sección Favoritos - Próximamente.");
    }//GEN-LAST:event_BfavoritosActionPerformed

    private void BpedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpedidosActionPerformed
        JOptionPane.showMessageDialog(null, "Sección Pedidos - Próximamente.");
    }//GEN-LAST:event_BpedidosActionPerformed

    private void BcarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcarritoActionPerformed
        carrito.mostrarCarrito();
    }//GEN-LAST:event_BcarritoActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        int conf = JOptionPane.showConfirmDialog(null,
            "¿Desea salir de MercaEZ?", "Salir",
            JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BsalirActionPerformed

    private void BperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BperfilActionPerformed
        JOptionPane.showMessageDialog(null, "Sección Perfil - Próximamente.");
    }//GEN-LAST:event_BperfilActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void txtDescricionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanelAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraMZ;
    private javax.swing.JButton Bcarrito;
    private javax.swing.JButton Bcatalogo;
    private javax.swing.JButton Bfavoritos;
    private javax.swing.JButton Bpedidos;
    private javax.swing.JButton Bperfil;
    private javax.swing.JButton Bsalir;
    private javax.swing.JLabel DescricionL;
    private javax.swing.JLabel Descripcion1;
    private javax.swing.JLabel INimagenL;
    private javax.swing.JLabel Icarrito;
    private javax.swing.JLabel Icatalogo;
    private javax.swing.JLabel Ifavoritos;
    private javax.swing.JLabel Ipedidos;
    private javax.swing.JLabel Iperfil;
    private javax.swing.JLabel NombreL;
    private javax.swing.JLabel PrecioL;
    private javax.swing.JLabel agregarPL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound3;
    private Clases.PanelRound panelRound4;
    private Clases.PanelRound pnlCarritoLleno;
    private Clases.PanelRound pnlCarritoVacio;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JScrollPane pnlScroll;
    private javax.swing.JTextField txtDescricion;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
