/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ccatalogo;

/**
 *
 * @author Laptop HP 255 G10
 */
public class PUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PUsuario.class.getName());

    /**
     * Creates new form PUsuario
     */
    public PUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
          panelusuario.setVisible(true);
    paneladmin.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bcatalogo = new javax.swing.JButton();
        Bfavoritos = new javax.swing.JButton();
        Bpedidos = new javax.swing.JButton();
        Bcarrito = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        Bperfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Icatalogo = new javax.swing.JLabel();
        Ifavoritos = new javax.swing.JLabel();
        Ipedidos = new javax.swing.JLabel();
        Icarrito = new javax.swing.JLabel();
        Iperfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        Lbmiperfil = new javax.swing.JLabel();
        panelRound2 = new Clases.PanelRound();
        panelRound3 = new Clases.PanelRound();
        panelRound4 = new Clases.PanelRound();
        LBusuario = new javax.swing.JLabel();
        Descripcion1 = new javax.swing.JLabel();
        panelRound5 = new Clases.PanelRound();
        Lbicono = new javax.swing.JLabel();
        panelRound6 = new Clases.PanelRound();
        LBmailIC = new javax.swing.JLabel();
        Lbemail = new javax.swing.JLabel();
        Descripcion2 = new javax.swing.JLabel();
        panelusuario = new Clases.PanelRound();
        LBescudo1 = new javax.swing.JLabel();
        LBrol1 = new javax.swing.JLabel();
        Descripcion4 = new javax.swing.JLabel();
        paneladmin = new Clases.PanelRound();
        LBescudo = new javax.swing.JLabel();
        LBrol = new javax.swing.JLabel();
        Descripcion3 = new javax.swing.JLabel();
        panelRound8 = new Clases.PanelRound();
        BotonCS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/iconoMZ.png"))); // NOI18N

        Bcatalogo.setBackground(new java.awt.Color(51, 255, 255));
        Bcatalogo.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bcatalogo.setText("Catalogo");
        Bcatalogo.setBorder(null);
        Bcatalogo.setBorderPainted(false);
        Bcatalogo.setContentAreaFilled(false);
        Bcatalogo.setFocusPainted(false);
        Bcatalogo.addActionListener(this::BcatalogoActionPerformed);

        Bfavoritos.setBackground(new java.awt.Color(51, 255, 255));
        Bfavoritos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bfavoritos.setText("Favoritos");
        Bfavoritos.setBorder(null);
        Bfavoritos.setBorderPainted(false);
        Bfavoritos.setContentAreaFilled(false);
        Bfavoritos.setFocusPainted(false);
        Bfavoritos.addActionListener(this::BfavoritosActionPerformed);

        Bpedidos.setBackground(new java.awt.Color(51, 255, 255));
        Bpedidos.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bpedidos.setText("pedidos");
        Bpedidos.setBorder(null);
        Bpedidos.setBorderPainted(false);
        Bpedidos.setContentAreaFilled(false);
        Bpedidos.setFocusPainted(false);
        Bpedidos.addActionListener(this::BpedidosActionPerformed);

        Bcarrito.setBackground(new java.awt.Color(51, 255, 255));
        Bcarrito.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bcarrito.setText("Carrito");
        Bcarrito.setBorder(null);
        Bcarrito.setBorderPainted(false);
        Bcarrito.setContentAreaFilled(false);
        Bcarrito.setFocusPainted(false);
        Bcarrito.addActionListener(this::BcarritoActionPerformed);

        Bsalir.setBackground(new java.awt.Color(51, 255, 255));
        Bsalir.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bsalir.setText("Salir");
        Bsalir.setBorder(null);
        Bsalir.setBorderPainted(false);
        Bsalir.setContentAreaFilled(false);
        Bsalir.setFocusPainted(false);
        Bsalir.addActionListener(this::BsalirActionPerformed);

        Bperfil.setBackground(new java.awt.Color(51, 255, 255));
        Bperfil.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Bperfil.setText("Perfil");
        Bperfil.setBorder(null);
        Bperfil.setBorderPainted(false);
        Bperfil.setContentAreaFilled(false);
        Bperfil.setFocusPainted(false);
        Bperfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bperfil.addActionListener(this::BperfilActionPerformed);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/salida (1).png"))); // NOI18N

        Icatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/revista-catalogo.png"))); // NOI18N

        Ifavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/corazon (1).png"))); // NOI18N

        Ipedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/reloj-tres (1).png"))); // NOI18N

        Icarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/carrito-de-compras.png"))); // NOI18N

        Iperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/usuario.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(Icatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ifavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bfavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ipedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bpedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Icarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bcarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iperfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Bperfil)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Icatalogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ifavoritos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ipedidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Icarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Iperfil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bcatalogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bfavoritos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bcarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bpedidos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bsalir)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 880, 60));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, 30));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        Lbmiperfil.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Lbmiperfil.setText("Mi perfil");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Lbmiperfil)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbmiperfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 40));

        panelRound2.setBackground(new java.awt.Color(204, 255, 255));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(0, 255, 255));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);

        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        LBusuario.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        LBusuario.setText("Usuario");

        Descripcion1.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion1.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion1.setText("Se@gmail.com");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addComponent(LBusuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Descripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);

        Lbicono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/usuario (2).png"))); // NOI18N
        Lbicono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbicono, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbicono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 29, 610, -1));

        panelRound6.setBackground(new java.awt.Color(204, 204, 204));
        panelRound6.setRoundBottomLeft(10);
        panelRound6.setRoundBottomRight(10);
        panelRound6.setRoundTopLeft(10);
        panelRound6.setRoundTopRight(10);

        LBmailIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/sobre (1).png"))); // NOI18N
        LBmailIC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Lbemail.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        Lbemail.setText("Correo");

        Descripcion2.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion2.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion2.setText("se@gmail.com");

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LBmailIC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbemail))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lbemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LBmailIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRound2.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 179, 621, 44));

        panelusuario.setBackground(new java.awt.Color(204, 204, 204));
        panelusuario.setRoundBottomLeft(10);
        panelusuario.setRoundBottomRight(10);
        panelusuario.setRoundTopLeft(10);
        panelusuario.setRoundTopRight(10);
        panelusuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBescudo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBescudo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/escudo-de-usuario.png"))); // NOI18N
        panelusuario.add(LBescudo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        LBrol1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        LBrol1.setText("Rol");
        panelusuario.add(LBrol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, -1, -1));

        Descripcion4.setBackground(new java.awt.Color(204, 204, 255));
        Descripcion4.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion4.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion4.setText("Usuario");
        panelusuario.add(Descripcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 381, 19));

        panelRound2.add(panelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 249, 620, -1));

        paneladmin.setPreferredSize(new java.awt.Dimension(450, 48));
        paneladmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBescudo.setText("jLabel7");
        paneladmin.add(LBescudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, -1));

        LBrol.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        LBrol.setText("Rol");
        paneladmin.add(LBrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, -1, -1));

        Descripcion3.setFont(new java.awt.Font("Inter", 1, 10)); // NOI18N
        Descripcion3.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion3.setText("admin");
        paneladmin.add(Descripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 29, 381, 19));

        panelRound2.add(paneladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 249, 620, -1));

        panelRound8.setBackground(new java.awt.Color(255, 255, 255));
        panelRound8.setRoundBottomLeft(50);
        panelRound8.setRoundBottomRight(50);
        panelRound8.setRoundTopLeft(50);
        panelRound8.setRoundTopRight(50);

        BotonCS.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        BotonCS.setForeground(new java.awt.Color(255, 0, 0));
        BotonCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/salir-alt.png"))); // NOI18N
        BotonCS.setText("   CERRAR SESIÓN");
        BotonCS.setBorder(null);
        BotonCS.setContentAreaFilled(false);
        BotonCS.setFocusPainted(false);
        BotonCS.addActionListener(this::BotonCSActionPerformed);

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonCS, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonCS, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 318, -1, -1));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 700, 390));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcatalogoActionPerformed
        JOptionPane.showMessageDialog(null, "Ya estás en el Catálogo.");
    }//GEN-LAST:event_BcatalogoActionPerformed

    private void BfavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfavoritosActionPerformed
        JOptionPane.showMessageDialog(null, "Sección Favoritos - Próximamente.");
    }//GEN-LAST:event_BfavoritosActionPerformed

    private void BpedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpedidosActionPerformed
        JOptionPane.showMessageDialog(null, "Sección Pedidos - Próximamente.");
    }//GEN-LAST:event_BpedidosActionPerformed

    private void BcarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcarritoActionPerformed
        carrito.mostrarCarrito();
    }//GEN-LAST:event_BcarritoActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        int conf = JOptionPane.showConfirmDialog(null,
            "¿Desea salir de MercaEZ?", "Salir",
            JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BsalirActionPerformed

    private void BperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BperfilActionPerformed
        JOptionPane.showMessageDialog(null, "Sección Perfil - Próximamente.");
    }//GEN-LAST:event_BperfilActionPerformed

    private void BotonCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcarrito;
    private javax.swing.JButton Bcatalogo;
    private javax.swing.JButton Bfavoritos;
    private javax.swing.JButton BotonCS;
    private javax.swing.JButton Bpedidos;
    private javax.swing.JButton Bperfil;
    private javax.swing.JButton Bsalir;
    private javax.swing.JLabel Descripcion1;
    private javax.swing.JLabel Descripcion2;
    private javax.swing.JLabel Descripcion3;
    private javax.swing.JLabel Descripcion4;
    private javax.swing.JLabel Icarrito;
    private javax.swing.JLabel Icatalogo;
    private javax.swing.JLabel Ifavoritos;
    private javax.swing.JLabel Ipedidos;
    private javax.swing.JLabel Iperfil;
    private javax.swing.JLabel LBescudo;
    private javax.swing.JLabel LBescudo1;
    private javax.swing.JLabel LBmailIC;
    private javax.swing.JLabel LBrol;
    private javax.swing.JLabel LBrol1;
    private javax.swing.JLabel LBusuario;
    private javax.swing.JLabel Lbemail;
    private javax.swing.JLabel Lbicono;
    private javax.swing.JLabel Lbmiperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    private Clases.PanelRound panelRound3;
    private Clases.PanelRound panelRound4;
    private Clases.PanelRound panelRound5;
    private Clases.PanelRound panelRound6;
    private Clases.PanelRound panelRound8;
    private Clases.PanelRound paneladmin;
    private Clases.PanelRound panelusuario;
    // End of variables declaration//GEN-END:variables
}
